# Generated by Django 4.0.1 on 2022-01-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Сообщение')),
                ('sender', models.EmailField(max_length=254, verbose_name='Адрес отправителя')),
                ('receiver', models.EmailField(max_length=254, verbose_name='Адрес получателя')),
                ('delay', models.SmallIntegerField(verbose_name='Отправить через (Секунды)')),
                ('send_status', models.BooleanField()),
                ('sending_time', models.TimeField()),
            ],
        ),
    ]
