# Generated by Django 4.0.1 on 2022-02-17 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='message',
            name='send_status',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sending_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Отправлено в '),
        ),
    ]
