# Generated by Django 4.0.1 on 2022-02-17 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Сообщение')),
                ('sender', models.EmailField(max_length=254, verbose_name='Адрес отправителя')),
                ('receiver', models.EmailField(max_length=254, verbose_name='Адрес получателя')),
                ('delay', models.SmallIntegerField(verbose_name='Отправить через (Секунды)')),
                ('send_status', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('sending_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Отправлено в ')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
