# Generated by Django 4.0.1 on 2022-02-18 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sending_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Отправлено в '),
        ),
    ]
