# Generated by Django 4.0.1 on 2022-02-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0002_alter_message_sending_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес отправителя'),
        ),
    ]
